//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Maple")]
[assembly: AssemblyVersion("0.0.1")]
[assembly: AssemblyFileVersion("0.0.1")]
[assembly: AssemblyInformationalVersion("0.0.0.1")]
[assembly: AssemblyCopyright("© 2019 Insire")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]

