using Maple.Core;
using Maple.Localization.Properties;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Input;

namespace Maple
{
    /// <summary>
    ///
    /// </summary>
    /// <seealso cref="Maple.Core.BaseDataListViewModel{Maple.Playlist, Maple.Data.Playlist}" />
    /// <seealso cref="Maple.Core.ILoadableViewModel" />
    /// <seealso cref="Maple.Core.ISaveableViewModel" />
    public class Playlists : BaseDataListViewModel<Playlist, Data.Playlist>, ISaveableViewModel, IPlaylistsViewModel
    {
        private readonly Func<IMediaRepository> _repositoryFactory;
        private readonly IPlaylistMapper _playlistMapper;

        /// <summary>
        /// Gets the play command.
        /// </summary>
        /// <value>
        /// The play command.
        /// </value>
        public ICommand PlayCommand { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="Playlists"/> class.
        /// </summary>
        /// <param name="log">The log.</param>
        /// <param name="repo">The repo.</param>
        /// <param name="dialogViewModel">The dialog view model.</param>
        public Playlists(ILocalizationService translationService, IMapleLog log, IPlaylistMapper playlistMapper, Func<IMediaRepository> repo, ISequenceProvider sequenceProvider)
            : base(log, translationService, sequenceProvider)
        {
            _repositoryFactory = repo ?? throw new ArgumentNullException(nameof(repo));
            _playlistMapper = playlistMapper ?? throw new ArgumentNullException(nameof(playlistMapper));

            AddCommand = new RelayCommand(Add, CanAdd);
        }

        /// <summary>
        /// Loads this instance.
        /// </summary>
        public override void Load()
        {
            _log.Info($"{_translationService.Translate(nameof(Resources.Loading))} {_translationService.Translate(nameof(Resources.Playlists))}");
            Clear();

            using (var context = _repositoryFactory())
                AddRange(context.GetAllPlaylists());

            SelectedItem = Items.FirstOrDefault();

            OnLoaded();
        }

        /// <summary>
        /// Saves this instance.
        /// </summary>
        public override void Save()
        {
            _log.Info($"{_translationService.Translate(nameof(Resources.Saving))} {_translationService.Translate(nameof(Resources.Playlists))}");
            using (var context = _repositoryFactory())
            {
                context.Save(this);
            }
        }

        // TODO order changing + sync, Commands, UserInteraction


        /// <summary>
        /// Creates and adds a new instance.
        /// </summary>
        /// <autogeneratedoc />
        public void Add()
        {
            var sequence = _sequenceProvider.Get(Items.Select(p => (ISequence)p).ToList());
            Add(_playlistMapper.GetNewPlaylist(sequence));
        }

        public bool CanAdd()
        {
            return Items != null;
        }

        public override Task SaveAsync()
        {
            return Task.Run(() => Save());
        }

        public override async Task LoadAsync()
        {
            _log.Info($"{_translationService.Translate(nameof(Resources.Loading))} {_translationService.Translate(nameof(Resources.Playlists))}");
            Clear();

            using (var context = _repositoryFactory())
            {
                var result = await context.GetAllPlaylistsAsync();
                AddRange(result);
            }

            SelectedItem = Items.FirstOrDefault();
            OnLoaded();
        }
    }
}
