namespace Maple.Data
{
    public class Option : BaseObject
    {
        /// <summary>
        /// Gets or sets the key for the ITranslationService.
        /// </summary>
        /// <value>
        /// The key.
        /// </value>
        /// <autogeneratedoc />
        public string Key { get; set; }

        public string Value { get; set; }

        public int Type { get; set; }
    }
}
