// <auto-generated />
using System;
using Maple.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Maple.Data.Migrations
{
    [DbContext(typeof(PlaylistContext))]
    [Migration("20190505105243_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Maple.Domain.MediaItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("SYSTEM");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description");

                    b.Property<long>("Duration");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(2048);

                    b.Property<int>("MediaItemType");

                    b.Property<int>("PlaylistId");

                    b.Property<int>("PrivacyStatus");

                    b.Property<int>("Sequence");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("UpdatedBy")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("SYSTEM");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("Maple.Domain.MediaPlayerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("SYSTEM");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100);

                    b.Property<bool>("IsPrimary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int?>("PlaylistId");

                    b.Property<int>("Sequence");

                    b.Property<string>("UpdatedBy")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("SYSTEM");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("Mediaplayers");
                });

            modelBuilder.Entity("Maple.Domain.OptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("SYSTEM");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Key")
                        .IsRequired();

                    b.Property<int>("Sequence");

                    b.Property<int>("Type");

                    b.Property<string>("UpdatedBy")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("SYSTEM");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Maple.Domain.PlaylistModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("SYSTEM");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<bool>("IsShuffeling");

                    b.Property<string>("Location");

                    b.Property<int?>("MediaPlayerId");

                    b.Property<int>("PrivacyStatus");

                    b.Property<int>("RepeatMode");

                    b.Property<int>("Sequence");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("UpdatedBy")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue("SYSTEM");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("MediaPlayerId")
                        .IsUnique();

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Maple.Domain.MediaItemModel", b =>
                {
                    b.HasOne("Maple.Domain.PlaylistModel", "Playlist")
                        .WithMany("MediaItems")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Maple.Domain.PlaylistModel", b =>
                {
                    b.HasOne("Maple.Domain.MediaPlayerModel", "MediaPlayer")
                        .WithOne("Playlist")
                        .HasForeignKey("Maple.Domain.PlaylistModel", "MediaPlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
