using System.Diagnostics;
using System.IO;

namespace Maple.Core
{
    /// <summary>
    ///
    /// </summary>
    /// <seealso cref="Maple.Core.MapleFileSystemContainerBase" />
    /// <seealso cref="Maple.Core.IFileSystemDirectory" />
    /// <autogeneratedoc />
    [DebuggerDisplay("Directory: {Name} IsContainer: {IsContainer}")]
    public class MapleDirectory : MapleFileSystemContainerBase, IFileSystemDirectory
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MapleDirectory"/> class.
        /// </summary>
        /// <param name="info">The information.</param>
        /// <param name="depth">The depth.</param>
        /// <param name="parent">The parent.</param>
        /// <autogeneratedoc />
        public MapleDirectory(DirectoryInfo info, IDepth depth, IFileSystemDirectory parent) : base(info.Name, info.FullName, depth, parent)
        {
            using (_busyStack.GetToken())
            {
                if (!Depth.IsMaxReached)
                    Refresh();
            }
        }

        /// <summary>
        /// Loads the meta data.
        /// </summary>
        /// <autogeneratedoc />
        public override void LoadMetaData()
        {
            var info = new DirectoryInfo(FullName);

            Exists = info.Exists;
            IsHidden = info.Attributes.HasFlag(FileAttributes.Hidden);
        }

        /// <summary>
        /// Deletes this instance.
        /// </summary>
        /// <autogeneratedoc />
        public override void Delete()
        {
            Directory.Delete(FullName);
            Refresh();
        }

        /// <summary>
        /// Determines whether this instance can delete.
        /// </summary>
        /// <returns>
        ///   <c>true</c> if this instance can delete; otherwise, <c>false</c>.
        /// </returns>
        /// <autogeneratedoc />
        public override bool CanDelete()
        {
            return Directory.Exists(FullName);
        }
    }
}
