using System.IO;
using System.Linq;
using System.Windows.Input;
using Maple.Domain;

namespace Maple.Core
{
    public class FileSystemViewModel : ViewModel
    {
        public ICommand SelectCommand { get; private set; }

        private IRangeObservableCollection<IFileSystemInfo> _selectedItems;
        public IRangeObservableCollection<IFileSystemInfo> SelectedItems
        {
            get { return _selectedItems; }
            private set { SetValue(ref _selectedItems, value); }
        }

        private IRangeObservableCollection<IFileSystemInfo> _selectedDetailItems;
        public IRangeObservableCollection<IFileSystemInfo> SelectedDetailItems
        {
            get { return _selectedDetailItems; }
            set { SetValue(ref _selectedDetailItems, value); }
        }

        private IRangeObservableCollection<MapleDrive> _drives;
        public IRangeObservableCollection<MapleDrive> Drives
        {
            get { return _drives; }
            private set { SetValue(ref _drives, value); }
        }

        private MapleFileSystemContainerBase _selectedItem;
        public MapleFileSystemContainerBase SelectedItem
        {
            get { return _selectedItem; }
            set { SetValue(ref _selectedItem, value, OnChanged: OnSelectedItemChanged); }
        }

        private string _filter;
        public string Filter
        {
            get { return _filter; }
            set { SetValue(ref _filter, value, OnChanged: () => SelectedItem.OnFilterChanged(Filter)); }
        }

        private bool _displayListView;
        public bool DisplayListView
        {
            get { return _displayListView; }
            set { SetValue(ref _displayListView, value); }
        }

        public FileSystemViewModel(IMessenger messenger)
            : base(messenger)
        {
            using (BusyStack.GetToken())
            {
                DisplayListView = false;

                Drives = new RangeObservableCollection<MapleDrive>();
                SelectedItems = new RangeObservableCollection<IFileSystemInfo>();
                SelectedDetailItems = new RangeObservableCollection<IFileSystemInfo>();

                var drives = DriveInfo.GetDrives()
                                        .Where(p => p.IsReady && p.DriveType != DriveType.CDRom && p.DriveType != DriveType.Unknown)
                                        .Select(p => new MapleDrive(p, new FileSystemDepth(0), Messenger))
                                        .ToList();
                Drives.AddRange(drives);

                SelectCommand = new RelayCommand<object>(SetSelectedItem, CanSetSelectedItem);
            }
        }

        private void OnSelectedItemChanged()
        {
            SelectedItem.Load();
            SelectedItem.LoadMetaData();

            Messenger.Publish(new FileSystemInfoChangedMessage(this, SelectedItem));
        }

        /// <summary>
        /// Sets the selected item.
        /// </summary>
        /// <param name="item">The item.</param>
        /// <autogeneratedoc />
        public void SetSelectedItem(object item)
        {
            var value = item as MapleFileSystemContainerBase;

            if (value == null)
                return;

            SelectedItem = value;
            SelectedItem.ExpandPath();
            SelectedItem.Parent.IsSelected = true;
        }

        private bool CanSetSelectedItem(object item)
        {
            var value = item as MapleFileSystemContainerBase;

            return value != null && value != SelectedItem;
        }
    }
}
