using System.Diagnostics;
using System.IO;

namespace Maple.Core
{
    /// <summary>
    ///
    /// </summary>
    /// <seealso cref="Maple.Core.MapleFileSystemBase" />
    /// <seealso cref="Maple.Core.IFileSystemFile" />
    /// <autogeneratedoc />
    [DebuggerDisplay("File: {Name} IsContainer: {IsContainer}")]
    public class MapleFile : MapleFileSystemBase, IFileSystemFile
    {
        public MapleFile(FileInfo info, IDepth depth, IFileSystemDirectory parent) : base(info.Name, info.FullName, depth, parent)
        {
            using (_busyStack.GetToken())
            {
                if (!Depth.IsMaxReached)
                {
                    Refresh();
                    IsExpanded = true;
                }
            }
        }

        /// <summary>
        /// Refreshes this instance.
        /// </summary>
        /// <autogeneratedoc />
        public override void Refresh()
        {
            using (_busyStack.GetToken())
            {
                OnFilterChanged(string.Empty);
            }
        }

        /// <summary>
        /// Called when [filter changed].
        /// </summary>
        /// <param name="filter">The filter.</param>
        /// <autogeneratedoc />
        public override void OnFilterChanged(string filter)
        {
            Filter = filter;
        }

        /// <summary>
        /// Loads the meta data.
        /// </summary>
        /// <autogeneratedoc />
        public override void LoadMetaData()
        {
            var info = new FileInfo(FullName);

            Exists = info.Exists;
            IsHidden = info.Attributes.HasFlag(FileAttributes.Hidden);
        }

        /// <summary>
        /// Deletes this instance.
        /// </summary>
        /// <autogeneratedoc />
        public override void Delete()
        {
            File.Delete(FullName);
            Parent.Refresh();
        }

        /// <summary>
        /// Determines whether this instance can delete.
        /// </summary>
        /// <returns>
        ///   <c>true</c> if this instance can delete; otherwise, <c>false</c>.
        /// </returns>
        /// <autogeneratedoc />
        public override bool CanDelete()
        {
            return File.Exists(FullName);
        }
    }
}
