using System.Windows;
using System.Windows.Controls;
using System.Windows.Interactivity;

namespace Maple.Core
{
    /// <summary>
    ///
    /// </summary>
    /// <seealso cref="System.Windows.Interactivity.Behavior{System.Windows.Controls.TreeView}" />
    /// <autogeneratedoc />
    public class SelectedTreeViewItemBehavior : Behavior<TreeView>
    {
        /// <summary>
        /// Gets or sets the selected item.
        /// </summary>
        /// <value>
        /// The selected item.
        /// </value>
        /// <autogeneratedoc />
        public object SelectedItem
        {
            get { return GetValue(SelectedItemProperty); }
            set { SetValue(SelectedItemProperty, value); }
        }

        /// <summary>
        /// The selected item property
        /// </summary>
        /// <autogeneratedoc />
        public static readonly DependencyProperty SelectedItemProperty = DependencyProperty.Register(
                                                                                nameof(SelectedItem),
                                                                                typeof(object),
                                                                                typeof(SelectedTreeViewItemBehavior),
                                                                                new UIPropertyMetadata(null, OnSelectedItemChanged));

        private static void OnSelectedItemChanged(DependencyObject sender, DependencyPropertyChangedEventArgs e)
        {
            var item = e.NewValue as TreeViewItem;

            item?.SetValue(TreeViewItem.IsSelectedProperty, true);
        }

        /// <summary>
        /// Called when [attached].
        /// </summary>
        /// <autogeneratedoc />
        protected override void OnAttached()
        {
            base.OnAttached();

            AssociatedObject.SelectedItemChanged += OnTreeViewSelectedItemChanged;
        }

        /// <summary>
        /// Called when [detaching].
        /// </summary>
        /// <autogeneratedoc />
        protected override void OnDetaching()
        {
            base.OnDetaching();

            if (AssociatedObject != null)
                AssociatedObject.SelectedItemChanged -= OnTreeViewSelectedItemChanged;
        }

        private void OnTreeViewSelectedItemChanged(object sender, RoutedPropertyChangedEventArgs<object> e)
        {
            SelectedItem = e.NewValue;
        }
    }
}
