using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Maple
{
    /// <summary>
    ///
    /// </summary>
    /// <seealso cref="System.IDisposable" />
    public interface IMediaRepository : IDisposable
    {
        /// <summary>
        /// Gets a value indicating whether this instance is busy.
        /// </summary>
        /// <value>
        ///   <c>true</c> if this instance is busy; otherwise, <c>false</c>.
        /// </value>
        bool IsBusy { get; }

        /// <summary>
        /// Gets the media item by playlist identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        /// <autogeneratedoc />
        IList<MediaItem> GetMediaItemByPlaylistId(int id);
        Task<IList<MediaItem>> GetMediaItemByPlaylistIdAsync(int id);

        /// <summary>
        /// Gets all media items.
        /// </summary>
        /// <returns></returns>
        IList<MediaItem> GetAllMediaItems();
        Task<IList<MediaItem>> GetAllMediaItemsAsync();

        /// <summary>
        /// Gets all optional media players.
        /// </summary>
        /// <returns></returns>
        IList<MediaPlayer> GetAllOptionalMediaPlayers();
        Task<IList<MediaPlayer>> GetAllOptionalMediaPlayersAsync();

        /// <summary>
        /// Gets all playlists.
        /// </summary>
        /// <returns></returns>
        IList<Playlist> GetAllPlaylists();
        Task<IList<Playlist>> GetAllPlaylistsAsync();

        /// <summary>
        /// Gets the media item by identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        MediaItem GetMediaItemById(int id);
        Task<MediaItem> GetMediaItemByIdAsync(int id);

        /// <summary>
        /// Gets the media player by identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        MediaPlayer GetMediaPlayerById(int id);
        Task<MediaPlayer> GetMediaPlayerByIdAsync(int id);

        /// <summary>
        /// Gets the playlist by identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns></returns>
        Playlist GetPlaylistById(int id);
        Task<Playlist> GetPlaylistByIdAsync(int id);

        /// <summary>
        /// Gets the main media player.
        /// </summary>
        /// <returns></returns>
        MediaPlayer GetMainMediaPlayer();
        Task<MediaPlayer> GetMainMediaPlayerAsync();

        /// <summary>
        /// Saves the specified item.
        /// </summary>
        /// <param name="item">The item.</param>
        void Save(MediaItem item, bool isRoot = true);
        /// <summary>
        /// Saves the specified player.
        /// </summary>
        /// <param name="player">The player.</param>
        void Save(MediaPlayer player, bool isRoot = true);
        /// <summary>
        /// Saves the specified players.
        /// </summary>
        /// <param name="players">The players.</param>
        void Save(IMediaPlayersViewModel players, bool isRoot = true);
        /// <summary>
        /// Saves the specified playlist.
        /// </summary>
        /// <param name="playlist">The playlist.</param>
        void Save(Playlist playlist, bool isRoot = true);
        /// <summary>
        /// Saves the specified playlists.
        /// </summary>
        /// <param name="playlists">The playlists.</param>
        void Save(Playlists playlists, bool isRoot = true);

        void Save(IMediaItemsViewModel mediaItems, bool isRoot = true);
    }
}