//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maple.Localization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maple.Localization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anwendung wird gestartet.
        /// </summary>
        public static string AppStart {
            get {
                return ResourceManager.GetString("AppStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiedergabegerät.
        /// </summary>
        public static string AudioDevice {
            get {
                return ResourceManager.GetString("AudioDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeren.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist bereits ein Dialog geöffnet. Es kann kein Weiterer geöffnet werden.
        /// </summary>
        public static string DialogOpenAlready {
            get {
                return ResourceManager.GetString("DialogOpenAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirigent.
        /// </summary>
        public static string Director {
            get {
                return ResourceManager.GetString("Director", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichert geleert.
        /// </summary>
        public static string DisposedState {
            get {
                return ResourceManager.GetString("DisposedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speicher wird geleert.
        /// </summary>
        public static string DisposingState {
            get {
                return ResourceManager.GetString("DisposingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dauer.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Wiedergabeliste aus einer Datei importieren.
        /// </summary>
        public static string FilePlaylistImport {
            get {
                return ResourceManager.GetString("FilePlaylistImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Wiedergabeliste anhand eines Ordners aus dem Dateisystem generieren und importieren.
        /// </summary>
        public static string FolderPlaylistImport {
            get {
                return ResourceManager.GetString("FolderPlaylistImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Insire/InsireBot-V2.
        /// </summary>
        public static string GithubProjectLink {
            get {
                return ResourceManager.GetString("GithubProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf der Datenbank befinden sich eine ungültige Anzahl an Einträgen für den Standardmediaplayer.
        /// </summary>
        public static string InvalidMediaplayerCountOnDBException {
            get {
                return ResourceManager.GetString("InvalidMediaplayerCountOnDBException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to darf nicht leer sein.
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprachen.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ort.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardmediaplayer.
        /// </summary>
        public static string MainMediaplayer {
            get {
                return ResourceManager.GetString("MainMediaplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es können keine weiteren Wiedergabelisten angelegt werden, da die maximale Anzahl erreicht wurde.
        /// </summary>
        public static string MaxPlaylistCountReachedException {
            get {
                return ResourceManager.GetString("MaxPlaylistCountReachedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation wird geladen.
        /// </summary>
        public static string NavigationLoad {
            get {
                return ResourceManager.GetString("NavigationLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation geladen.
        /// </summary>
        public static string NavigationLoaded {
            get {
                return ResourceManager.GetString("NavigationLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysieren.
        /// </summary>
        public static string Parse {
            get {
                return ResourceManager.GetString("Parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiedergabe.
        /// </summary>
        public static string Playback {
            get {
                return ResourceManager.GetString("Playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiedergabemodus.
        /// </summary>
        public static string PlaybackMode {
            get {
                return ResourceManager.GetString("PlaybackMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Titel wiederholen.
        /// </summary>
        public static string PlaybackModeAll {
            get {
                return ResourceManager.GetString("PlaybackModeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keinen Titel wiederholen.
        /// </summary>
        public static string PlaybackModeNone {
            get {
                return ResourceManager.GetString("PlaybackModeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einen Titel wiederholen.
        /// </summary>
        public static string PlaybackModeOne {
            get {
                return ResourceManager.GetString("PlaybackModeOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zufällige Wiedergabe.
        /// </summary>
        public static string PlaybackShuffle {
            get {
                return ResourceManager.GetString("PlaybackShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiedergabeliste.
        /// </summary>
        public static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiedergabeliste hinzufügen.
        /// </summary>
        public static string PlaylistAdd {
            get {
                return ResourceManager.GetString("PlaylistAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelle Wiedergabeliste.
        /// </summary>
        public static string PlaylistCurrent {
            get {
                return ResourceManager.GetString("PlaylistCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiedergabelisten.
        /// </summary>
        public static string Playlists {
            get {
                return ResourceManager.GetString("Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entfernen.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Beschränkung.
        /// </summary>
        public static string ResctrictionNone {
            get {
                return ResourceManager.GetString("ResctrictionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zugriffsbeschränkung.
        /// </summary>
        public static string Restriction {
            get {
                return ResourceManager.GetString("Restriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Zugriff.
        /// </summary>
        public static string RestrictionRestricted {
            get {
                return ResourceManager.GetString("RestrictionRestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen gespeichert.
        /// </summary>
        public static string SavedState {
            get {
                return ResourceManager.GetString("SavedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichere.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderungen werden gespeichert.
        /// </summary>
        public static string SavingState {
            get {
                return ResourceManager.GetString("SavingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateiauswahl.
        /// </summary>
        public static string SelectFiles {
            get {
                return ResourceManager.GetString("SelectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordnerauswahl.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maple.
        /// </summary>
        public static string ShellTitle {
            get {
                return ResourceManager.GetString("ShellTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themen.
        /// </summary>
        public static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video hinzufügen.
        /// </summary>
        public static string VideoAdd {
            get {
                return ResourceManager.GetString("VideoAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lautstärke.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtubeservice wird geladen.
        /// </summary>
        public static string YoutubeLoad {
            get {
                return ResourceManager.GetString("YoutubeLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtubeservice geladen.
        /// </summary>
        public static string YoutubeLoaded {
            get {
                return ResourceManager.GetString("YoutubeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Widergabeliste von Youtube importieren.
        /// </summary>
        public static string YoutubePlaylistImport {
            get {
                return ResourceManager.GetString("YoutubePlaylistImport", resourceCulture);
            }
        }
    }
}
